[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
  let g:onedark_termcolors=256
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
  \   'colorscheme': 'onedark'
  \}
'''

[[plugins]]
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo  = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo  = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo  = 'cakebaker/scss-syntax.vim'
on_ft = 'scss'

[[plugins]]
repo  = 'jelera/vim-javascript-syntax'
on_ft = 'js'

[[plugins]]
repo  = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd', 'md']
hook_add = '''
  let g:vim_markdown_frontmatter = 1
  let g:vim_markdown_math = 1
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
